version: 2.1
jobs:
  toolchains:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - run:
          name: 'Setup environment variables'
          command: |
            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/master?filter=successful&limit=30"
            echo export LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '[.[] | select(.build_parameters.CIRCLE_JOB != "toolchains")][0].vcs_revision'` >> $BASH_ENV
            cat $BASH_ENV
            docker system info
      - checkout
      - run:
          name: 'Docker login'
          working_directory: barretenberg
          command: |
            docker login -u aztecprotocolci -p "${DOCKERHUB_PASSWORD}"
      - run:
          name: 'cmake'
          working_directory: barretenberg
          command: |
            if git diff --name-only ${LAST_SUCCESSFUL_COMMIT} ${CIRCLE_SHA1} | grep -q dockerfiles/Dockerfile.cmake; then
              docker-compose build cmake
              docker push aztecprotocol/cmake:3.16.5
            fi
      - run:
          name: 'gcc'
          working_directory: barretenberg
          command: |
            if git diff --name-only ${LAST_SUCCESSFUL_COMMIT} ${CIRCLE_SHA1} | grep -q dockerfiles/Dockerfile.gcc; then
              docker-compose build gcc
              docker push aztecprotocol/gcc:9
            fi
      - run:
          name: 'clang'
          working_directory: barretenberg
          command: |
            if git diff --name-only ${LAST_SUCCESSFUL_COMMIT} ${CIRCLE_SHA1} | grep -q dockerfiles/Dockerfile.clang; then
              docker-compose build clang
              docker push aztecprotocol/clang:9.0.0
            fi
      # - run:
      #     name: 'crosstool-ng'
      #     working_directory: barretenberg
      #     command: |
      #       if git diff --name-only ${LAST_SUCCESSFUL_COMMIT} ${CIRCLE_SHA1} | grep -q dockerfiles/Dockerfile.crosstool-ng; then
      #         docker-compose build crosstool-ng
      #         docker push aztecprotocol/crosstool-ng:1.24.0
      #       fi
      # - run:
      #     name: 'crosstool-ng-arm64'
      #     working_directory: barretenberg
      #     command: |
      #       if git diff --name-only ${LAST_SUCCESSFUL_COMMIT} ${CIRCLE_SHA1} | grep -q dockerfiles/Dockerfile.crosstool-ng-arm64; then
      #         docker-compose build crosstool-ng-arm64
      #         docker push aztecprotocol/crosstool-ng-arm64:latest
      #       fi
      #     no_output_timeout: '60m'
      # - run:
      #     name: 'mingw'
      #     working_directory: barretenberg
      #     command: |
      #       if git diff --name-only ${LAST_SUCCESSFUL_COMMIT} ${CIRCLE_SHA1} | grep -q dockerfiles/Dockerfile.mingw; then
      #         docker-compose build mingw
      #         docker push aztecprotocol/mingw:latest
      #       fi
      #     no_output_timeout: '60m'

  x86_64-linux-gcc:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Build'
          working_directory: barretenberg
          command: |
            docker pull aztecprotocol/gcc:9
            docker-compose build x86_64-linux-gcc

  x86_64-linux-clang:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Build'
          working_directory: barretenberg
          command: |
            docker pull aztecprotocol/clang:9.0.0
            docker-compose build x86_64-linux-clang
            docker-compose run x86_64-linux-clang

  wasm-linux-clang:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Build'
          working_directory: barretenberg
          command: |
            docker pull aztecprotocol/clang:9.0.0
            docker-compose build wasm-linux-clang

  x86_64-win32-mingw:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Build'
          working_directory: barretenberg
          command: docker-compose build x86_64-win32-mingw

  arm64-linux-gcc:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: 'Build'
          working_directory: barretenberg
          command: docker-compose build arm64-linux-gcc

workflows:
  build:
    jobs:
      - toolchains
      - x86_64-linux-gcc:
          requires:
            - toolchains
      - x86_64-linux-clang:
          requires:
            - toolchains
      - wasm-linux-clang:
          requires:
            - toolchains
      # - x86_64-win32-mingw:
      #     requires:
      #       - toolchains
      # - arm64-linux-gcc:
      #     requires:
      #       - toolchains
